services:
  react-app:
    build:
      context: .
      args:
        REACT_APP_NEWS_API_KEY: "${REACT_APP_NEWS_API_KEY}"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_NEWS_API_KEY=${REACT_APP_NEWS_API_KEY}
    stdin_open: true
    tty: true
